---
engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
    config:
      file: invalid-rule.xml
ratings:
  paths: []
include_paths:
  - src/
exclude_paths:
  - gradle/
  - .gradle/

