---
engines:
  sonar-java:
    enabled: false
  fixme:
    enabled: false
  duplication:
    enabled: false
  pmd:
    enabled: true
ratings:
  paths: []
include_paths:
  - src/
exclude_paths:
  - gradle/
  - .gradle/
  - src/main/java/com/google/common/collect/Lists.java
