---
engines:
  sonar-java:
    enabled: false
  fixme:
    enabled: false
  duplication:
    enabled: false
  structure:
    enabled: false
  pmd:
    enabled: true
ratings:
  paths: []
include_paths:
  - src/
exclude_paths:
  - gradle/
  - .gradle/
