---
engines:
  checkstyle:
    enabled: true
  pmd:
    enabled: true
  sonar-java:
    enabled: true
    channel: beta
ratings:
  paths: []
include_paths:
  - src/
exclude_paths:
  - gradle/
  - .gradle/

