#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cc-test-reporter before-build
gradle test coberturaReport

echo "Copying coverage"
cp build/reports/cobertura/coverage.xml cobertura.xml

echo "Sending report"
cc-test-reporter after-build -t cobertura -r b4ead4c6885ca55c0105e464e360e752baad1839c1fe1fec0360f0a77d33f60c -e http://localhost:4000/v1/test_reports
