/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// FIXME
public class Library {
  public static void main(String[] args) {
  }

  public void bar() {
    System.out.println("test");
    System.out.println("test");
    System.out.println("test");
    System.out.println("test");
    System.out.println("test");
  }

}
