package pkg;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
  String[] args = new String[0];

    @Test public void testSomeLibraryMethod() {
        Library.main(args);
        new Library().bar();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
